# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Get_Token',
        ),
    ]
